### ISSUE TITLE
Cannot validate certificate from peer cmd

### ISSUE THREAD

**Issue by zhuyuanmao** [hyperledger/cello#340]
## Expected Behavior

peer cmd can be executed on api-engine container via given ordered URL or peer URL. 

## Current Behavior

Received Client TLS handshake failed error with the cmd below
```
./peer channel create -o 172.17.0.1:57803 -c channel -f /opt/cello/test1/channel-artifacts/channel.tx --tls --cafile /opt/cello/org1.cello.com/crypto-config/ordererOrganizations/cello.com/msp/tlscacerts/tlsca.cello.com-cert.pem
```

## Steps to Reproduce

1. Create a user with org
2. Create a docker agent.
3. Create orderer, peer nodes and network
4. execute peer cmd.

## Context (Environment)

* OS: Ubuntu 
* Architecture:  x86_64
* Docker version:  Docker version 20.10.9, build c2ea9bc
* Docker compose version: docker-compose version 1.29.2, build 5becea4c
* Kubernetes version:

## Detailed Description and log

If I use `127.0.0.1:57803` as the order URL,  it will be failed to create new connections.
```shell
./peer channel create -o 127.0.0.1:57803 -c channel -f /opt/cello/test1/channel-artifacts/channel.tx --tls --cafile /opt/cello/org1.cello.com/crypto-config/ordererOrganizations/cello.com/msp/tlscacerts/tlsca.cello.com-cert.pem 
```
```
Error: failed to create deliver client for orderer: orderer client failed to connect to 127.0.0.1:57803: failed to create new connection: connection error: desc = "transport: error while dialing: dial tcp 127.0.0.1:57803: connect: connection refused"
```

I executed this cmd on api-engine container, `172.17.0.1` is the docker brige network for inter-containers communication. 
```shell
./peer channel create -o 172.17.0.1:57803 -c channel -f /opt/cello/test1/channel-artifacts/channel.tx --tls --cafile /opt/cello/org1.cello.com/crypto-config/ordererOrganizations/cello.com/msp/tlscacerts/tlsca.cello.com-cert.pem
```
```
2021-10-22 17:26:43.248 UTC [comm.tls] ClientHandshake -> ERRO 001 Client TLS handshake failed after 36.089387ms with error: x509: cannot validate certificate for 172.17.0.1 because it doesn't contain any IP SANs remoteaddress=172.17.0.1:18793
2021-10-22 17:26:44.265 UTC [comm.tls] ClientHandshake -> ERRO 002 Client TLS handshake failed after 4.58043ms with error: x509: cannot validate certificate for 172.17.0.1 because it doesn't contain any IP SANs remoteaddress=172.17.0.1:18793
2021-10-22 17:26:45.772 UTC [comm.tls] ClientHandshake -> ERRO 003 Client TLS handshake failed after 7.195286ms with error: x509: cannot validate certificate for 172.17.0.1 because it doesn't contain any IP SANs remoteaddress=172.17.0.1:18793
```
Docker containers
```
CONTAINER ID   IMAGE                            COMMAND                  CREATED          STATUS          PORTS                                                                                                                              NAMES
3dfb6b9da380   yeasy/hyperledger-fabric:2.2.0   "bash /tmp/init.sh '…"   27 seconds ago   Up 6 seconds    7050/tcp, 7054/tcp, 8443/tcp, 9443/tcp, 0.0.0.0:32315->7051/tcp, :::32315->7051/tcp, 0.0.0.0:10192->7053/tcp, :::10192->7053/tcp   cello-hlf-peer-peer0
ef0e1a40653c   yeasy/hyperledger-fabric:2.2.0   "bash /tmp/init.sh o…"   27 seconds ago   Up 6 seconds    7051/tcp, 7054/tcp, 8443/tcp, 9443/tcp, 0.0.0.0:36384->7050/tcp, :::36384->7050/tcp                                                cello-hlf-orderer-orderer0
2e52e105f6c5   yeasy/hyperledger-fabric:2.2.0   "bash /tmp/init.sh '…"   27 seconds ago   Up 6 seconds    7050/tcp, 7054/tcp, 8443/tcp, 9443/tcp, 0.0.0.0:55769->7051/tcp, :::55769->7051/tcp, 0.0.0.0:42385->7053/tcp, :::42385->7053/tcp   cello-hlf-peer-peer1
cd981524fc61   hyperledger/cello-agent-docker   "gunicorn server:app…"   2 minutes ago    Up 2 minutes    127.0.0.1:2375->2375/tcp, 0.0.0.0:5001->5001/tcp, :::5001->5001/tcp                                                                cello-agent-docker
7f102f9fe062   postgres:11.1                    "docker-entrypoint.s…"   21 minutes ago   Up 21 minutes   0.0.0.0:5432->5432/tcp, :::5432->5432/tcp                                                                                          cello-postgres
```
Orderer.yaml (`/opt/cello/org1.cello.com/crypto-config/ordererOrganizations/cello.com/orderers/orderer0.cello.com/orderer.yaml`)
```yaml
ChannelParticipation:
  Enabled: false
  RemoveStorage: false
Consensus:
  SnapDir: /var/hyperledger/production/orderer/etcdraft/snapshot
  WALDir: /var/hyperledger/production/orderer/etcdraft/wal
Debug:
  BroadcastTraceDir: null
  DeliverTraceDir: null
FileLedger:
  Location: /var/hyperledger/production/orderer
General:
  Authentication:
    TimeWindow: 15m
  BCCSP:
    Default: SW
    PKCS11:
      FileKeyStore:
        KeyStore: null
      Hash: null
      Label: null
      Library: null
      Pin: null
      Security: null
    SW:
      FileKeyStore:
        KeyStore: null
      Hash: SHA2
      Security: 256
  BootstrapFile: genesis.block
  BootstrapMethod: file
  Cluster:
    ClientCertificate: null
    ClientPrivateKey: null
    ListenAddress: null
    ListenPort: null
    SendBufferSize: 10
    ServerCertificate: null
    ServerPrivateKey: null
  Keepalive:
    ServerInterval: 7200s
    ServerMinInterval: 60s
    ServerTimeout: 20s
  ListenAddress: 0.0.0.0
  ListenPort: 7050
  LocalMSPDir: msp
  LocalMSPID: Org1.cello.comOrdererMSP
  Profile:
    Address: 0.0.0.0:6060
    Enabled: false
  TLS:
    Certificate: tls/server.crt
    ClientAuthRequired: false
    ClientRootCAs: null
    Enabled: true
    PrivateKey: tls/server.key
    RootCAs:
    - tls/ca.crt
Kafka:
  Retry:
    Consumer:
      RetryBackoff: 2s
    LongInterval: 5m
    LongTotal: 12h
    Metadata:
      RetryBackoff: 250ms
      RetryMax: 3
    NetworkTimeouts:
      DialTimeout: 10s
      ReadTimeout: 10s
      WriteTimeout: 10s
    Producer:
      RetryBackoff: 100ms
      RetryMax: 3
    ShortInterval: 5s
    ShortTotal: 10m
  SASLPlain:
    Enabled: false
    Password: null
    User: null
  TLS:
    Certificate: null
    Enabled: false
    PrivateKey: null
    RootCAs: null
  Topic:
    ReplicationFactor: 3
  Verbose: false
  Version: null
Metrics:
  Provider: disabled
  Statsd:
    Address: 127.0.0.1:8125
    Network: udp
    Prefix: null
    WriteInterval: 30s
Operations:
  ListenAddress: 127.0.0.1:8443
  TLS:
    Certificate: null
    ClientAuthRequired: false
    ClientRootCAs: []
    Enabled: false
    PrivateKey: null

```
peer core.yaml  (`/opt/cello/org1.cello.com/crypto-config/peerOrganizations/org1.cello.com/peers/peer0.org1.cello.com/ core.yaml` )
```yaml
chaincode:
  builder: $(DOCKER_NS)/fabric-ccenv:$(TWO_DIGIT_VERSION)
  executetimeout: 30s
  externalBuilders: []
  golang:
    dynamicLink: false
    runtime: $(DOCKER_NS)/fabric-baseos:$(TWO_DIGIT_VERSION)
  id:
    name: null
    path: null
  installTimeout: 300s
  java:
    runtime: $(DOCKER_NS)/fabric-javaenv:$(TWO_DIGIT_VERSION)
  keepalive: 0
  logging:
    format: '%{color}%{time:2006-01-02 15:04:05.000 MST} [%{module}] %{shortfunc}
      -> %{level:.4s} %{id:03x}%{color:reset} %{message}'
    level: info
    shim: warning
  mode: net
  node:
    runtime: $(DOCKER_NS)/fabric-nodeenv:$(TWO_DIGIT_VERSION)
  pull: false
  startuptimeout: 300s
  system:
    _lifecycle: enable
    cscc: enable
    escc: enable
    lscc: enable
    qscc: enable
    vscc: enable
ledger:
  blockchain: null
  history:
    enableHistoryDatabase: true
  pvtdataStore:
    collElgProcDbBatchesInterval: 1000
    collElgProcMaxDbBatchSize: 5000
  state:
    couchDBConfig:
      cacheSize: 64
      couchDBAddress: 127.0.0.1:5984
      createGlobalChangesDB: false
      internalQueryLimit: 1000
      maxBatchUpdateSize: 1000
      maxRetries: 3
      maxRetriesOnStartup: 10
      password: null
      requestTimeout: 35s
      username: null
      warmIndexesAfterNBlocks: 1
    stateDatabase: goleveldb
    totalQueryLimit: 100000
metrics:
  provider: disabled
  statsd:
    address: 127.0.0.1:8125
    network: udp
    prefix: null
    writeInterval: 10s
operations:
  listenAddress: 127.0.0.1:9443
  tls:
    cert:
      file: null
    clientAuthRequired: false
    clientRootCAs:
      files: []
    enabled: false
    key:
      file: null
peer:
  BCCSP:
    Default: SW
    PKCS11:
      Hash: null
      Label: null
      Library: null
      Pin: null
      Security: null
    SW:
      FileKeyStore:
        KeyStore: null
      Hash: SHA2
      Security: 256
  address: peer0.org1.cello.com:7051
  addressAutoDetect: false
  authentication:
    timewindow: 15m
  chaincodeAddress: peer0.org1.cello.com:7052
  chaincodeListenAddress: 0.0.0.0:7052
  client:
    connTimeout: 3s
  deliveryclient:
    addressOverrides: null
    connTimeout: 3s
    reConnectBackoffThreshold: 3600s
    reconnectTotalTimeThreshold: 3600s
  discovery:
    authCacheEnabled: true
    authCacheMaxSize: 1000
    authCachePurgeRetentionRatio: 0.75
    enabled: true
    orgMembersAllowedAccess: false
  fileSystemPath: /var/hyperledger/production
  gossip:
    aliveExpirationTimeout: 25s
    aliveTimeInterval: 5s
    bootstrap: 127.0.0.1:7051
    connTimeout: 2s
    dialTimeout: 3s
    digestWaitTime: 1s
    election:
      leaderAliveThreshold: 10s
      leaderElectionDuration: 5s
      membershipSampleInterval: 1s
      startupGracePeriod: 15s
    endpoint: null
    externalEndpoint: peer0.org1.cello.com:7051
    maxBlockCountToStore: 10
    maxConnectionAttempts: 120
    maxPropagationBurstLatency: 10ms
    maxPropagationBurstSize: 10
    membershipTrackerInterval: 5s
    msgExpirationFactor: 20
    orgLeader: true
    propagateIterations: 1
    propagatePeerNum: 3
    publishCertPeriod: 10s
    publishStateInfoInterval: 4s
    pullInterval: 4s
    pullPeerNum: 3
    pvtData:
      btlPullMargin: 10
      implicitCollectionDisseminationPolicy:
        maxPeerCount: 1
        requiredPeerCount: 0
      pullRetryThreshold: 60s
      pushAckTimeout: 3s
      reconcileBatchSize: 10
      reconcileSleepInterval: 1m
      reconciliationEnabled: true
      skipPullingInvalidTransactionsDuringCommit: false
      transientstoreMaxBlockRetention: 1000
    reconnectInterval: 25s
    recvBuffSize: 20
    requestStateInfoInterval: 4s
    requestWaitTime: 1500ms
    responseWaitTime: 2s
    sendBuffSize: 200
    skipBlockVerification: false
    state:
      batchSize: 10
      blockBufferSize: 20
      checkInterval: 10s
      enabled: false
      maxRetries: 3
      responseTimeout: 3s
    stateInfoRetentionInterval: null
    useLeaderElection: false
  handlers:
    authFilters:
    - name: DefaultAuth
    - name: ExpirationCheck
    decorators:
    - name: DefaultDecorator
    endorsers:
      escc:
        library: null
        name: DefaultEndorsement
    validators:
      vscc:
        library: null
        name: DefaultValidation
  id: peer0.org1.cello.com
  keepalive:
    client:
      interval: 60s
      timeout: 20s
    deliveryClient:
      interval: 60s
      timeout: 20s
    interval: 7200s
    minInterval: 60s
    timeout: 20s
  limits:
    concurrency:
      deliverService: 2500
      endorserService: 2500
  listenAddress: 0.0.0.0:7051
  localMspId: Org1.cello.comMSP
  localMspType: bccsp
  mspConfigPath: msp
  networkId: dev
  profile:
    enabled: false
    listenAddress: 0.0.0.0:6060
  tls:
    cert:
      file: tls/server.crt
    clientAuthRequired: false
    clientCert:
      file: null
    clientKey:
      file: null
    clientRootCAs:
      files:
      - tls/ca.crt
    enabled: true
    key:
      file: tls/server.key
    rootcert:
      file: tls/ca.crt
  validatorPoolSize: null
vm:
  docker:
    attachStdout: false
    hostConfig:
      Dns: null
      LogConfig:
        Config:
          max-file: '5'
          max-size: 50m
        Type: json-file
      Memory: 2147483648
      NetworkMode: host
    tls:
      ca:
        file: docker/ca.crt
      cert:
        file: docker/tls.crt
      enabled: false
      key:
        file: docker/tls.key
  endpoint: unix:///var/run/docker.sock

```
